import { Experience, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'all', label: 'Trending', icon: '🔥' },
  { id: 'tours', label: 'Tours', icon: '🗺️' },
  { id: 'food', label: 'Food & Drink', icon: '🍷' },
  { id: 'adventure', label: 'Adventure', icon: '🪂' },
  { id: 'art', label: 'Art & Culture', icon: '🎨' },
  { id: 'nightlife', label: 'Nightlife', icon: '🌙' },
  { id: 'wellness', label: 'Wellness', icon: '🧘' },
];

// Using Mixkit free stock videos for demo purposes
export const EXPERIENCES: Experience[] = [
  {
    id: '1',
    title: 'Sintra Treasure Hunt',
    description: 'Follow a map and a backpack of "magic" tools through Sintra\'s mysterious forests. Discover hidden gems and local myths in this interactive adventure suitable for all ages.',
    category: 'adventure',
    price: 22,
    currency: '€',
    rating: 4.8,
    reviews: 124,
    location: 'Sintra, Portugal',
    imageUrl: 'https://images.unsplash.com/photo-1590632607996-33827d092244?q=80&w=800&auto=format&fit=crop',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-forest-stream-in-the-sunlight-529-large.mp4',
    duration: '3 hours',
  },
  {
    id: '2',
    title: 'Sunset Sailing on the Tagus',
    description: 'Experience Lisbon from a different perspective. Enjoy a glass of Portuguese wine while watching the sun set over the iconic 25 de Abril Bridge.',
    category: 'tours',
    price: 45,
    currency: '€',
    rating: 4.9,
    reviews: 89,
    location: 'Lisbon, Portugal',
    imageUrl: 'https://images.unsplash.com/photo-1544256272-38507204f2f0?q=80&w=800&auto=format&fit=crop',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-aerial-view-of-a-sailboat-in-the-sea-1300-large.mp4',
    duration: '2 hours',
  },
  {
    id: '3',
    title: 'Authentic Fado Night',
    description: 'Immerse yourself in the soul of Lisbon. A candlelit dinner accompanied by live Fado music in one of Alfama\'s oldest houses.',
    category: 'art',
    price: 60,
    currency: '€',
    rating: 4.7,
    reviews: 210,
    location: 'Alfama, Lisbon',
    imageUrl: 'https://images.unsplash.com/photo-1514525253440-b393452e8d26?q=80&w=800&auto=format&fit=crop',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-playing-guitar-at-a-concert-close-up-1596-large.mp4',
    duration: '3 hours',
  },
  {
    id: '4',
    title: 'Pastel de Nata Workshop',
    description: 'Learn the secrets of Portugal\'s famous custard tarts from a master baker. Bake your own batch and enjoy them warm with cinnamon.',
    category: 'food',
    price: 35,
    currency: '€',
    rating: 5.0,
    reviews: 342,
    location: 'Baixa, Lisbon',
    imageUrl: 'https://images.unsplash.com/photo-1530182745778-958b4f177c8e?q=80&w=800&auto=format&fit=crop',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-baking-bread-in-a-traditional-oven-4197-large.mp4',
    duration: '1.5 hours',
  },
  {
    id: '5',
    title: 'Arrábida Hidden Beaches',
    description: 'Kayak through crystal clear waters and discover secret beaches accessible only by sea. Snorkeling gear included.',
    category: 'adventure',
    price: 55,
    currency: '€',
    rating: 4.9,
    reviews: 76,
    location: 'Setúbal, Portugal',
    imageUrl: 'https://images.unsplash.com/photo-1534349762913-96c221292021?q=80&w=800&auto=format&fit=crop',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-waves-coming-to-the-beach-5016-large.mp4',
    duration: '4 hours',
  },
  {
    id: '6',
    title: 'Lisbon Street Art Tour',
    description: 'Explore the open-air gallery of Lisbon streets. See works by Vhils, Bordalo II, and other world-renowned urban artists.',
    category: 'art',
    price: 20,
    currency: '€',
    rating: 4.6,
    reviews: 55,
    location: 'Bairro Alto, Lisbon',
    imageUrl: 'https://images.unsplash.com/photo-1522066848773-8d02be043922?q=80&w=800&auto=format&fit=crop',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-graffiti-artist-painting-on-a-wall-4623-large.mp4',
    duration: '2 hours',
  },
  {
    id: '7',
    title: 'Rooftop Cocktail Experience',
    description: 'Sip on signature cocktails at the highest point in the city. The perfect start to a vibrant night out.',
    category: 'nightlife',
    price: 30,
    currency: '€',
    rating: 4.5,
    reviews: 112,
    location: 'Principe Real, Lisbon',
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-bartender-making-a-cocktail-with-shaker-4416-large.mp4',
    duration: '2 hours',
  },
  {
    id: '8',
    title: 'Tile Painting Workshop',
    description: 'Paint your own traditional Portuguese Azulejo tile to take home as a unique souvenir. Guided by local artisans.',
    category: 'art',
    price: 28,
    currency: '€',
    rating: 4.8,
    reviews: 98,
    location: 'Mouraria, Lisbon',
    imageUrl: 'https://images.unsplash.com/photo-1627918805720-31295e4e844a?q=80&w=800&auto=format&fit=crop',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-pottery-art-4182-large.mp4',
    duration: '2 hours',
  },
];
