-- ============================================
-- Add short_title column + bulk UPDATE all experiences
-- Run in: Supabase Dashboard → SQL Editor
-- ============================================

ALTER TABLE experiences ADD COLUMN IF NOT EXISTS short_title text;

UPDATE experiences SET short_title = 'Stories, Art, Food & Music' WHERE id = 9;
UPDATE experiences SET short_title = 'Sintra Full-Day 4x4 Off-Road' WHERE id = 13;
UPDATE experiences SET short_title = 'Pilot For a Day' WHERE id = 14;
UPDATE experiences SET short_title = 'Sunset Hike, Tapas & Wine' WHERE id = 27;
UPDATE experiences SET short_title = 'Eat & Drink Like a Local' WHERE id = 124;
UPDATE experiences SET short_title = 'Undiscovered Food & Wine Tour' WHERE id = 125;
UPDATE experiences SET short_title = 'Sintra & Cascais Day Trip' WHERE id = 126;
UPDATE experiences SET short_title = 'Alfama - Lisbon''s Old Town' WHERE id = 127;
UPDATE experiences SET short_title = 'Food & Wine Walking Tour' WHERE id = 128;
UPDATE experiences SET short_title = 'Sunset & Wine Sailing Tour' WHERE id = 129;
UPDATE experiences SET short_title = 'Traditional Cruise - Fado & Wine' WHERE id = 130;
UPDATE experiences SET short_title = 'Traditional Cruise - Fado & Wine' WHERE id = 131;
UPDATE experiences SET short_title = 'Tastings in Alfama & Mouraria' WHERE id = 132;
UPDATE experiences SET short_title = 'Live Escape Hunt Lisbon' WHERE id = 133;
UPDATE experiences SET short_title = 'Wineries, Cheese & Coastal Views' WHERE id = 134;
UPDATE experiences SET short_title = 'Dolphin Watching with Biologist' WHERE id = 135;
UPDATE experiences SET short_title = 'A Culinary Crossroads' WHERE id = 136;
UPDATE experiences SET short_title = 'Wineries, Cheese & Full Lunch' WHERE id = 137;
UPDATE experiences SET short_title = 'Pastel de Nata Masterclass' WHERE id = 138;
UPDATE experiences SET short_title = 'Arrábida Kayak & Coasteering' WHERE id = 139;
UPDATE experiences SET short_title = 'Surf Lesson in Costa da Caparica' WHERE id = 140;
UPDATE experiences SET short_title = 'Street Art Walking Workshop' WHERE id = 141;
UPDATE experiences SET short_title = 'Traditional Cooking Class' WHERE id = 142;
UPDATE experiences SET short_title = 'Intimate Live Fado Show' WHERE id = 143;
UPDATE experiences SET short_title = 'Relaxing Sailboat Cruise' WHERE id = 144;
UPDATE experiences SET short_title = 'Arrábida Safari' WHERE id = 145;
UPDATE experiences SET short_title = 'The Slave Trade in Lisbon - Tour' WHERE id = 146;
UPDATE experiences SET short_title = 'Petiscos Cooking Class' WHERE id = 147;
UPDATE experiences SET short_title = 'Portuguese Tile Painting Workshop' WHERE id = 148;
UPDATE experiences SET short_title = 'Street Photography Photowalk' WHERE id = 149;
UPDATE experiences SET short_title = 'Lisbon Sketching Tour' WHERE id = 150;
UPDATE experiences SET short_title = 'Lisbon Photography Masterclass' WHERE id = 151;
UPDATE experiences SET short_title = 'Age of Discoveries Walking Tour' WHERE id = 152;
UPDATE experiences SET short_title = 'Arrábida Wine Tour' WHERE id = 153;
UPDATE experiences SET short_title = 'Surf Experience with a Local' WHERE id = 154;
UPDATE experiences SET short_title = 'Setúbal Wine Tour' WHERE id = 155;
UPDATE experiences SET short_title = 'Arrábida Kayak & Snorkel' WHERE id = 156;
UPDATE experiences SET short_title = 'Kayak Adventure' WHERE id = 157;
UPDATE experiences SET short_title = 'Portuguese Cooking Class' WHERE id = 158;
UPDATE experiences SET short_title = 'Portuguese Cooking Experience' WHERE id = 159;
UPDATE experiences SET short_title = 'Discover Óbidos Medieval Tales' WHERE id = 160;
UPDATE experiences SET short_title = 'Évora: Roman Temple & Megalithic' WHERE id = 161;
UPDATE experiences SET short_title = 'Dolphin Watching' WHERE id = 162;
UPDATE experiences SET short_title = 'Corinthia Signature Massage' WHERE id = 163;
UPDATE experiences SET short_title = 'Arrábida Coasteering' WHERE id = 164;
UPDATE experiences SET short_title = 'Fátima, Batalha, Nazaré & Óbidos' WHERE id = 165;
UPDATE experiences SET short_title = 'Sintra, Cabo da Roca & Cascais' WHERE id = 166;
UPDATE experiences SET short_title = 'Culinary Journey Through History' WHERE id = 167;
UPDATE experiences SET short_title = 'Lisbon Fado Night' WHERE id = 168;
UPDATE experiences SET short_title = 'Sintra & Cascais 4x4 L& Rover' WHERE id = 169;
UPDATE experiences SET short_title = 'Sunset Sailing Cruise' WHERE id = 170;
UPDATE experiences SET short_title = 'Fado, Dinner & Panoramic Tour' WHERE id = 177;
UPDATE experiences SET short_title = 'Lisbon Oceanario: Aquarium Ticket' WHERE id = 178;
UPDATE experiences SET short_title = 'Private Tour to Espichel Cape' WHERE id = 179;
UPDATE experiences SET short_title = 'Lisbon by Night' WHERE id = 180;
UPDATE experiences SET short_title = 'Fado Musical Experience' WHERE id = 181;
UPDATE experiences SET short_title = 'Balloon Ride - Coruche' WHERE id = 182;
UPDATE experiences SET short_title = 'Óbidos & Nazaré Giant Waves' WHERE id = 183;
UPDATE experiences SET short_title = 'Sunset Sailboat Tour' WHERE id = 184;
UPDATE experiences SET short_title = 'Corinthia - Half Day Spa' WHERE id = 185;
UPDATE experiences SET short_title = 'Private Local Cooking Class' WHERE id = 186;
UPDATE experiences SET short_title = 'Half-Day Kayak Tour in Sesimbra' WHERE id = 187;
UPDATE experiences SET short_title = 'Lisbon''s Jewish Sephardic History' WHERE id = 188;
UPDATE experiences SET short_title = 'Jurassic Hiking Tour' WHERE id = 189;
UPDATE experiences SET short_title = 'Arrábida Natural Park Hiking' WHERE id = 190;
UPDATE experiences SET short_title = 'Fado Show With Wine & History' WHERE id = 191;
UPDATE experiences SET short_title = 'the Salazar Dictatorship Legacy' WHERE id = 192;
UPDATE experiences SET short_title = 'Évora & Monsaraz from Lisbon' WHERE id = 193;
UPDATE experiences SET short_title = 'Kayak & Snorkeling Adventure' WHERE id = 194;
UPDATE experiences SET short_title = 'Tandem Paragliding Flight' WHERE id = 195;
UPDATE experiences SET short_title = 'Cascais Walking Tour' WHERE id = 196;
UPDATE experiences SET short_title = 'Kayaking & Snorkeling Adventure' WHERE id = 197;
UPDATE experiences SET short_title = 'Ericeira: 5-Day Surf Course' WHERE id = 198;
UPDATE experiences SET short_title = 'Sintra Historical Jeep Adventure' WHERE id = 199;
UPDATE experiences SET short_title = 'Night Cruise' WHERE id = 200;
UPDATE experiences SET short_title = 'Nazare Big Waves & Óbidos' WHERE id = 201;
UPDATE experiences SET short_title = 'Immersive Theatre Show' WHERE id = 202;
UPDATE experiences SET short_title = 'Birdwatching Boat Tour' WHERE id = 203;
UPDATE experiences SET short_title = 'City of Spies Walking Tour' WHERE id = 204;
UPDATE experiences SET short_title = 'The Unholy Secrets Walking Tour' WHERE id = 205;
UPDATE experiences SET short_title = 'Helicopter Tour over Belém' WHERE id = 206;
UPDATE experiences SET short_title = 'Vegan Food & Culture Walking Tour' WHERE id = 207;
UPDATE experiences SET short_title = 'Erotic Cabaret Show & Dinner' WHERE id = 208;
UPDATE experiences SET short_title = 'Antique Car Tour' WHERE id = 209;
UPDATE experiences SET short_title = 'Arrábida Scuba Diving' WHERE id = 210;
UPDATE experiences SET short_title = 'Comporta Beach Horseback Riding' WHERE id = 226;
UPDATE experiences SET short_title = 'Self-Drive Sightseeing Tour' WHERE id = 227;
UPDATE experiences SET short_title = 'Indoor Skydiving Experience' WHERE id = 228;
UPDATE experiences SET short_title = 'Deep Sea Fishing Trip' WHERE id = 229;
UPDATE experiences SET short_title = 'Ah Amália Immersive Experience' WHERE id = 230;
UPDATE experiences SET short_title = 'Guided Coast Kayak Tour' WHERE id = 231;
UPDATE experiences SET short_title = 'Guided Quad Tour by the Coast' WHERE id = 232;
UPDATE experiences SET short_title = 'Treasure Hunt & Tour' WHERE id = 233;
UPDATE experiences SET short_title = 'Guided Off-Road Buggy Ride' WHERE id = 234;
UPDATE experiences SET short_title = 'Caving - Arrábida Natural Park' WHERE id = 235;
UPDATE experiences SET short_title = 'Immersive Escape Game' WHERE id = 236;
UPDATE experiences SET short_title = 'Surf Lesson - Carcavelos' WHERE id = 237;
UPDATE experiences SET short_title = 'Vintage Citroën 2CV Food Tour' WHERE id = 238;
UPDATE experiences SET short_title = 'Sintra & Cascais E-Bike Tour' WHERE id = 239;
UPDATE experiences SET short_title = 'Kickstart Street Art Walking Tour' WHERE id = 240;
UPDATE experiences SET short_title = 'Lisbon Hills E-Bike Tour' WHERE id = 241;
UPDATE experiences SET short_title = 'Cascais Rock Climbing Experience' WHERE id = 242;
UPDATE experiences SET short_title = 'Ocean Scuba Diving Experience' WHERE id = 243;
UPDATE experiences SET short_title = 'Paragliding' WHERE id = 244;
UPDATE experiences SET short_title = 'Douro Valley Wine Tour' WHERE id = 245;
UPDATE experiences SET short_title = 'Tile Painting & Cocktails' WHERE id = 246;
UPDATE experiences SET short_title = 'Porto Surf Experience' WHERE id = 247;
UPDATE experiences SET short_title = 'Pastel de Nata Workshop' WHERE id = 248;
UPDATE experiences SET short_title = 'Douro River Boat Cruise' WHERE id = 249;
UPDATE experiences SET short_title = 'Douro Valley Tour' WHERE id = 250;
UPDATE experiences SET short_title = 'Clérigos Church Videomapping Show' WHERE id = 251;
UPDATE experiences SET short_title = 'Six Bridges Tour' WHERE id = 252;
UPDATE experiences SET short_title = 'Authentic Food & Wine Tour' WHERE id = 253;
UPDATE experiences SET short_title = 'Charming Sailboat Cruise' WHERE id = 254;
UPDATE experiences SET short_title = 'Workshop Cook & Taste' WHERE id = 255;
UPDATE experiences SET short_title = 'Port Wine Lodges Tour & Tasting' WHERE id = 256;
UPDATE experiences SET short_title = 'Douro Valley Small-Group Tour' WHERE id = 257;
UPDATE experiences SET short_title = 'The Ultimate Full-Meal Food Tour' WHERE id = 258;
UPDATE experiences SET short_title = 'Aveiro & Surroundings' WHERE id = 259;
UPDATE experiences SET short_title = 'Livraria Lello Entry Ticket' WHERE id = 260;
UPDATE experiences SET short_title = 'Porto Highlights E-Bike Tour' WHERE id = 261;
UPDATE experiences SET short_title = 'Suspension Bridge & Passadiços' WHERE id = 262;
UPDATE experiences SET short_title = 'Douro Valey Walking' WHERE id = 263;
UPDATE experiences SET short_title = 'Fado by Casa da Guitarra' WHERE id = 264;
UPDATE experiences SET short_title = 'Braga & Guimarães Tour' WHERE id = 265;
UPDATE experiences SET short_title = 'Jewish Heritage Walking Tour' WHERE id = 266;
UPDATE experiences SET short_title = 'Buggy Tour Offroad' WHERE id = 267;
UPDATE experiences SET short_title = 'Private Tour in a Classic Car' WHERE id = 268;
UPDATE experiences SET short_title = 'Gerês Park Waterfalls & Nature' WHERE id = 269;
UPDATE experiences SET short_title = 'Cooking & Eating at Local Home' WHERE id = 270;
UPDATE experiences SET short_title = 'Porto Food Tour of 8 Tastings' WHERE id = 271;
UPDATE experiences SET short_title = 'LGBTour Porto' WHERE id = 272;
UPDATE experiences SET short_title = 'Best of Porto Walking Tour' WHERE id = 273;
UPDATE experiences SET short_title = 'Viana, P. Lima & Braga from Porto' WHERE id = 274;
UPDATE experiences SET short_title = 'Craft Beer & Food Tour' WHERE id = 275;
UPDATE experiences SET short_title = 'Port Wine Cocktails Workshop' WHERE id = 276;
UPDATE experiences SET short_title = '1/2 Day Walking Photo Tour' WHERE id = 277;
UPDATE experiences SET short_title = 'Culture and Food Traditions' WHERE id = 278;
UPDATE experiences SET short_title = 'Private Bike Tour' WHERE id = 279;
UPDATE experiences SET short_title = 'Douro 4x4 Adventure' WHERE id = 280;
UPDATE experiences SET short_title = 'Pinhão Hiking Tour' WHERE id = 281;
UPDATE experiences SET short_title = '4X4 Private Tour' WHERE id = 282;
UPDATE experiences SET short_title = 'City & Mountain E-Bike Tour' WHERE id = 283;
UPDATE experiences SET short_title = 'Clay, Ceramics & Tea Workshop' WHERE id = 284;
UPDATE experiences SET short_title = 'Can-Am Experience' WHERE id = 285;
UPDATE experiences SET short_title = 'Wakeboarding Experience' WHERE id = 286;
UPDATE experiences SET short_title = 'Horseback Riding Tour' WHERE id = 287;
UPDATE experiences SET short_title = 'Serra D''Arga Canyoning' WHERE id = 288;
UPDATE experiences SET short_title = 'Melgaço Rafting' WHERE id = 289;
UPDATE experiences SET short_title = 'Guided Bike Tour' WHERE id = 290;
UPDATE experiences SET short_title = 'Hike, Dive & Dine' WHERE id = 291;
UPDATE experiences SET short_title = 'Costume Museum' WHERE id = 292;
UPDATE experiences SET short_title = 'Gil Eannes Hospital Ship Museum' WHERE id = 293;
UPDATE experiences SET short_title = 'The Roots Gallery & Wine' WHERE id = 294;
UPDATE experiences SET short_title = 'Professional Family Photoshoot' WHERE id = 295;
UPDATE experiences SET short_title = 'Canoa Raft' WHERE id = 296;
UPDATE experiences SET short_title = 'E-Foil & Wakeboarding Experience' WHERE id = 297;
UPDATE experiences SET short_title = 'Melgaço: CanoaRaft Adventure' WHERE id = 298;
UPDATE experiences SET short_title = 'Combo Dolphin & Benagil Tour' WHERE id = 299;
UPDATE experiences SET short_title = 'Cruise Benagil & Carvoeiro Caves' WHERE id = 300;
UPDATE experiences SET short_title = 'Ponta da Piedade Caves Kayak Tour' WHERE id = 301;
UPDATE experiences SET short_title = 'E-Bike Sightseeing Guided Tour' WHERE id = 302;
UPDATE experiences SET short_title = 'Dolphin Watch with Biologist' WHERE id = 303;
UPDATE experiences SET short_title = 'Wine Tasting Tour' WHERE id = 304;
UPDATE experiences SET short_title = 'Pastel de Nata Baking Class' WHERE id = 305;
UPDATE experiences SET short_title = 'Algarve Classic Food Tour' WHERE id = 306;
UPDATE experiences SET short_title = 'Walking Tour with Brodie (AUS)' WHERE id = 307;
UPDATE experiences SET short_title = 'Sagres Natural Park Jeep Tour' WHERE id = 308;
UPDATE experiences SET short_title = 'Bottom Fishing Lagos' WHERE id = 309;
UPDATE experiences SET short_title = 'Morning Beach Hatha Flow Yoga' WHERE id = 310;
UPDATE experiences SET short_title = 'Coasteering & Snorkeling' WHERE id = 311;
UPDATE experiences SET short_title = 'Group Surf Lessons For All Levels' WHERE id = 312;
UPDATE experiences SET short_title = 'Jeep Safari with Lunch' WHERE id = 313;
UPDATE experiences SET short_title = 'Guided Scuba Diving (Beginners)' WHERE id = 314;
UPDATE experiences SET short_title = 'Market & Cataplana Cooking Class' WHERE id = 315;
UPDATE experiences SET short_title = 'Horseriding' WHERE id = 316;
UPDATE experiences SET short_title = 'Silves, Caldas & Monchique Wines' WHERE id = 317;
UPDATE experiences SET short_title = 'Kayak at Ponta da Piedade' WHERE id = 318;
UPDATE experiences SET short_title = 'Jeep Sunset Safari' WHERE id = 319;
UPDATE experiences SET short_title = 'Monchique & Silves Guided Trip' WHERE id = 320;
UPDATE experiences SET short_title = 'Food, Wine & Culture Tour' WHERE id = 321;
UPDATE experiences SET short_title = 'Around The Island in Two Days' WHERE id = 322;
UPDATE experiences SET short_title = 'Sunrise Hike - Pico Do Arieiro' WHERE id = 323;
UPDATE experiences SET short_title = 'Jeep Tour to Natural Pools' WHERE id = 324;
UPDATE experiences SET short_title = 'Cliff Skywalk Open Roof 4X4' WHERE id = 325;
UPDATE experiences SET short_title = 'Whale & Dolphin Watching' WHERE id = 326;
UPDATE experiences SET short_title = 'Madeira Valley of the Nuns Tour' WHERE id = 327;
UPDATE experiences SET short_title = 'Old Funchal Walking Tour' WHERE id = 328;
UPDATE experiences SET short_title = 'Time Travel - Columbus Flag Ship' WHERE id = 329;
UPDATE experiences SET short_title = 'Wine & Food Tour in Funchal' WHERE id = 330;
UPDATE experiences SET short_title = 'Sunrise Hike Pico do Areeiro' WHERE id = 331;
UPDATE experiences SET short_title = 'Farm-to-Table with Views' WHERE id = 332;
UPDATE experiences SET short_title = 'Levada do Caldeirão Verde Hike' WHERE id = 333;
UPDATE experiences SET short_title = 'Full Day Off-Road Tour' WHERE id = 334;
UPDATE experiences SET short_title = 'Wine, Skywalk, 4x4 Open Roof' WHERE id = 335;
UPDATE experiences SET short_title = 'Canyoning' WHERE id = 336;
UPDATE experiences SET short_title = 'Scuba Diving (Beginners)' WHERE id = 337;
UPDATE experiences SET short_title = 'Madeira Sidecar Adventure' WHERE id = 338;
UPDATE experiences SET short_title = 'Fado Show with Wine & History' WHERE id = 339;
UPDATE experiences SET short_title = 'Mountain Walk' WHERE id = 340;
UPDATE experiences SET short_title = 'Scuba Diving' WHERE id = 341;
UPDATE experiences SET short_title = 'Rabacal Lakes & Fountains Walk' WHERE id = 342;
UPDATE experiences SET short_title = 'Off-Road Adrenaline' WHERE id = 343;
UPDATE experiences SET short_title = 'Coasteering & Snorkeling' WHERE id = 344;
UPDATE experiences SET short_title = 'Jeep, Zipline & Volcanic Pools' WHERE id = 345;
UPDATE experiences SET short_title = 'P. Arieiro & Ruivo Hike Transfer' WHERE id = 346;
UPDATE experiences SET short_title = 'Caldeirao Verde Hiking Transfer' WHERE id = 347;
UPDATE experiences SET short_title = 'Bodyboard Experience' WHERE id = 348;
UPDATE experiences SET short_title = 'Off-Road Buggy Driving' WHERE id = 349;
UPDATE experiences SET short_title = 'Diving Sharks & Rays - Aquarium' WHERE id = 350;
UPDATE experiences SET short_title = 'Surf lesson - Porto da Cruz' WHERE id = 351;
