-- Insert Hotel Picks experiences into Supabase
-- These are staff recommendations: Clara, Joel, and Gale's favorite spots

-- Clara's Pick: Kayak Tour Atlantic Coast (Experience)
INSERT INTO experiences (
  title,
  description,
  short_description,
  category,
  price,
  currency,
  rating,
  location,
  address,
  image_url,
  images,
  video_url,
  duration,
  highlights,
  included,
  max_group_size,
  cancellation_policy,
  important_info,
  is_active,
  staff_pick,
  staff_member
) VALUES (
  'Kayak Tour Atlantic Coast',
  'Perfect for adventure seekers! The caves and cliffs are incredible, and you might see dolphins! This is an unforgettable experience exploring the stunning coastline of Portugal.',
  'Explore dramatic caves and cliffs by kayak on the Atlantic coast',
  'Hotel Picks',
  45.00,
  'EUR',
  4.9,
  'Atlantic Coast',
  'Praia do Guincho, Cascais',
  'https://images.unsplash.com/photo-1493934558415-9d19f0b2b4d2?q=80&w=800&auto=format&fit=crop',
  ARRAY['https://images.unsplash.com/photo-1493934558415-9d19f0b2b4d2?q=80&w=800&auto=format&fit=crop'],
  null,
  '3 hours',
  ARRAY['Sea cave exploration', 'Dolphin watching opportunity', 'Professional guide', 'Stunning coastal views'],
  ARRAY['Kayak equipment', 'Life jacket', 'Waterproof bag', 'Guide'],
  8,
  'Free cancellation up to 24 hours before the experience',
  'Must know how to swim. Minimum age: 12 years old.',
  true,
  'Clara',
  'Concierge'
);

-- Joel's Pick: Time Out Market (Restaurant)
INSERT INTO experiences (
  title,
  description,
  short_description,
  category,
  price,
  currency,
  rating,
  location,
  address,
  image_url,
  images,
  video_url,
  duration,
  highlights,
  included,
  max_group_size,
  cancellation_policy,
  important_info,
  is_active,
  staff_pick,
  staff_member
) VALUES (
  'Time Out Market',
  'Can''t decide what to eat? This food hall has the best chefs in Lisbon all under one roof! My personal favorite is the seafood section. A must-visit for food lovers!',
  'Lisbon''s best chefs and restaurants in one amazing food hall',
  'Hotel Picks',
  25.00,
  'EUR',
  4.8,
  'Cais do Sodré',
  'Av. 24 de Julho 49, 1200-479 Lisboa',
  'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=800&auto=format&fit=crop',
  ARRAY['https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=800&auto=format&fit=crop'],
  null,
  '2 hours',
  ARRAY['40+ food stalls', 'Michelin-starred chefs', 'Live music', 'Vibrant atmosphere'],
  ARRAY['Entrance (free - pay only for food)'],
  null,
  'No cancellation needed - drop by anytime',
  'Gets very busy during lunch and dinner hours. Best to visit early!',
  true,
  'Joel',
  'Front Desk Manager'
);

-- Gale's Pick: LX Factory (Cool Place in Lisbon)
INSERT INTO experiences (
  title,
  description,
  short_description,
  category,
  price,
  currency,
  rating,
  location,
  address,
  image_url,
  images,
  video_url,
  duration,
  highlights,
  included,
  max_group_size,
  cancellation_policy,
  important_info,
  is_active,
  staff_pick,
  staff_member
) VALUES (
  'LX Factory',
  'Hip creative hub in an old industrial complex. Great for shopping, coffee, and Instagram photos! The bookstore Ler Devagar is absolutely stunning. Perfect afternoon spot!',
  'Trendy creative hub with shops, cafes, and stunning architecture',
  'Hotel Picks',
  0.00,
  'EUR',
  4.7,
  'Alcântara',
  'R. Rodrigues de Faria 103, 1300-501 Lisboa',
  'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?q=80&w=800&auto=format&fit=crop',
  ARRAY['https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?q=80&w=800&auto=format&fit=crop'],
  null,
  '2-3 hours',
  ARRAY['Ler Devagar bookstore', 'Street art', 'Boutique shops', 'Rooftop bars', 'Creative atmosphere'],
  ARRAY['Free to visit'],
  null,
  'No cancellation needed - open to public',
  'Best visited in the afternoon. Sunday has a great flea market!',
  true,
  'Gale',
  'Guest Relations'
);
