-- ============================================
-- Batch Caparica-2: 8 Viator experiences — Sesimbra/Arrábida/Almada area
-- Data fetched via Viator Partner API (exp-api-key: 0a9b6163-...)
-- display_order: 226–233
-- Run in: Supabase Dashboard → SQL Editor
-- ============================================

-- 226: Portuguese Food Experience in Almada (5588968P3) — EUR 35 / 3h30min
-- 227: Sesimbra Discovery by Kayak (10127P6) — EUR 25 / 3h ★4.95 (84)
-- 228: Half-Day Kayak Tour in Sesimbra (75380P3) — EUR 35 / 3h ★4.78 (49)
-- 229: Arrabida Dolphin & Whale Watching with Biologist (15178P4) — EUR 29.90 / 3h ★4.92 (248)
-- 230: Kayaking and Snorkeling in Sesimbra with Photos (304049P2) — EUR 25 / 3h ★4.89 (74)
-- 231: Arrabida Natural Park and Sesimbra Day Trip from Lisbon (6999SMLBIG) — EUR 45 / 8h ★4.63 (27)
-- 232: Underwater Viewing Tour along the Coast of Sesimbra (124473P1) — EUR 18 / 2h ★4.83 (35)
-- 233: Private Jeep Tour from Lisbon — Arrabida, Sesimbra and Beach Picnic (349639P1) — EUR 109 / 7h ★5.0 (48)

INSERT INTO experiences (operator_id, title, description, short_description, location, address, latitude, longitude, price, currency, duration, max_group_size, category, image_url, images, video_url, highlights, included, languages, cancellation_policy, rating, review_count, city, is_active, display_order, affiliate_url, affiliate_provider) VALUES
(40,'Portuguese Food Experience in Almada','A perfect blend of hands-on learning with an authentic dive into Portuguese culture. We don''t just teach recipes, we share stories, traditions, and secrets behind each dish, using fresh, local ingredients.','Hands-on Portuguese food workshop in Almada — recipes, stories and traditions with fresh local ingredients. Lunch included.','Almada','Almada (meeting point confirmed on booking)',38.6761,-9.1569,35.0,'EUR','3h 30min',NULL,'Local Cooking','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/16/23/13/1e.jpg','["https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/16/23/13/1e.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/16/23/13/a2.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/16/23/12/1a.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/16/23/12/60.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/15/d3/13/18.jpg"]'::jsonb,NULL,'["Hands-on cooking with authentic Portuguese recipes","Stories and traditions behind every dish","Fresh local ingredients","Lunch and beverages included","Small group experience in Almada"]'::jsonb,'["Lunch","Carbonated beverages","Tea and coffee"]'::jsonb,'["English","Portuguese"]'::jsonb,'Free cancellation up to 24h before',NULL,0,'Almada',true,226,'https://www.viator.com/en-GB/tours/Almada/Get-Creative-with-Immersive-Portuguese-Culture-Workshops/d51024-5588968P3?pid=P00285354&mcid=42383&medium=link','Viator'),
(40,'Sesimbra Discovery by Kayak','Spend an exciting day on the water with this 3-hour guided kayak tour of the Sesimbra coast. You will be amazed with the cliffs, caves and tunnels that characterize Sesimbra''s Natural Park. You will reach and stop at one of the most beautiful beaches in Portugal, Ribeira do Cavalo. A professional kayak guide will provide all the necessary gear before leading you on a gorgeous tour. Paddle 6-10 km through the Luiz de Saldanha Maritime Reserve. Lisbon pickup available.','3h guided kayak tour of Sesimbra coast — sea cliffs, caves, tunnels and a stop at Ribeira do Cavalo beach.','Sesimbra','Sesimbra Harbour, Sesimbra',38.4430,-9.1012,25.0,'EUR','3h',NULL,'Micro Adventures','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/11/89/b1/8a.jpg','["https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/11/89/b1/8a.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/11/89/b1/86.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/11/89/b2/69.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/b2/a0/dc.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/11/89/b1/8e.jpg"]'::jsonb,NULL,'["Kayak through cliffs, caves and tunnels in Arrábida Nature Park","Stop at Ribeira do Cavalo — one of Portugal''s most beautiful beaches","Paddle 6-10 km through the Luiz de Saldanha Maritime Reserve","Professional guide and all gear provided","Lisbon pickup option available"]'::jsonb,'["Snacks and water","Professional guide"]'::jsonb,'["English","Portuguese"]'::jsonb,'Free cancellation up to 24h before',4.95,84,'Sesimbra',true,227,'https://www.viator.com/en-GB/tours/Setubal-District/Lisbon-by-kayak/d5016-10127P6?pid=P00285354&mcid=42383&medium=link','Viator'),
(40,'Half-Day Kayak Tour in Sesimbra','Within an hour distance from Lisbon, this is a nature experience you will like to share with your family and friends. Using very stable double-seat sit-on-top Kayaks, you will comfortably and effortlessly paddle along these incredible landscapes.','Half-day sit-on-top kayak along Sesimbra''s stunning natural coastline — suitable for all, 1h from Lisbon.','Sesimbra','Sesimbra, Setubal District',38.4430,-9.1012,35.0,'EUR','3h',NULL,'Micro Adventures','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/09/e5/b7/d9.jpg','["https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/09/e5/b7/d9.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/06/74/87/2d.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/09/e5/b7/ab.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/09/e5/b6/8c.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/09/e5/b6/81.jpg"]'::jsonb,NULL,'["Stable sit-on-top kayaks — ideal for families and beginners","Stunning coastal scenery 1 hour from Lisbon","All safety equipment provided","Paddle through protected natural park waters","Great for groups and friends"]'::jsonb,'["Life jacket","Waterproof bag","Backboard","Sit-on-top canoe","Paddle","Insurance"]'::jsonb,'["English","Portuguese"]'::jsonb,'Free cancellation up to 24h before',4.78,49,'Sesimbra',true,228,'https://www.viator.com/en-GB/tours/Setubal-District/Kayak-Tour/d5016-75380P3?pid=P00285354&mcid=42383&medium=link','Viator'),
(40,'Sesimbra: Arrabida Dolphin and Whale Watching with Biologist','Experience the magic of the Atlantic with Sesimbra''s premier dolphin and whale watching tour, with 100% cetacean sightings, just a short drive from Lisbon. Cruise offshore the breathtaking Arrabida sheltered coast — UNESCO Biosphere Reserve, and be led by your biologist and seasoned crew to encounter playful dolphins and majestic whales. Snorkel in hidden turquoise bays and taste the famous local wine.','3h dolphin and whale watching with a marine biologist — 100% cetacean sighting guarantee in Arrabida UNESCO Biosphere Reserve.','Sesimbra','Sesimbra Marina, Sesimbra',38.4430,-9.1012,29.9,'EUR','3h',NULL,'Outdoors','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/10/3e/ab/a3.jpg','["https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/10/3e/ab/a3.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0c/01/7e/af.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/15/c0/c6/40.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/10/3e/ab/9f.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/15/c0/c6/29.jpg"]'::jsonb,NULL,'["100% cetacean sighting guarantee","Led by a marine biologist","Arrabida coast — UNESCO Biosphere Reserve","Snorkeling in hidden turquoise bays","Perfect for families and wildlife lovers"]'::jsonb,'["Welcome drink","Local guide","Bottled water","National Park fees","Snorkeling equipment","Environmental Management Charge"]'::jsonb,'["English","Portuguese"]'::jsonb,'Free cancellation up to 24h before',4.92,248,'Sesimbra',true,229,'https://www.viator.com/en-GB/tours/Setubal-District/Dolphin-Watch-Tour-in-Sesimbra/d5016-15178P4?pid=P00285354&mcid=42383&medium=link','Viator'),
(40,'Kayaking and Snorkeling in Sesimbra with Photos','The instructors know the Sesimbra coast inside out. All instructors are certified and have extensive experience with water activities — the goal is for you to have fun safely. Explore the crystal-clear waters of the Arrabida Natural Park by kayak and snorkel through its marine reserve. Professional photos included.','3h kayaking + snorkeling in Sesimbra — certified instructors, all equipment and professional photos included.','Sesimbra','Sesimbra, Setubal District',38.4430,-9.1012,25.0,'EUR','3h',NULL,'Micro Adventures','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/10/4a/28/1f.jpg','["https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/10/4a/28/1f.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0f/fe/ee/10.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0f/2a/08/90.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0f/fe/ee/e0.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0f/fe/ee/e1.jpg"]'::jsonb,NULL,'["Certified instructors with deep local knowledge","Kayak and snorkel through Arrabida Marine Reserve","Professional photos of your session included","All equipment provided","Private transport from Lisbon available"]'::jsonb,'["Private transportation","Snorkeling equipment","Insurance","Kayaking equipment"]'::jsonb,'["English","Portuguese"]'::jsonb,'Free cancellation up to 24h before',4.89,74,'Sesimbra',true,230,'https://www.viator.com/en-GB/tours/Setubal-District/All-inclusive-Kayaking-and-snorkeling-in-Arrabida-from-Lisbon/d5016-304049P2?pid=P00285354&mcid=42383&medium=link','Viator'),
(40,'Arrabida Natural Park and Sesimbra Day Trip from Lisbon','Meet your guide at your Lisbon hotel and cross the Tagus heading south. Drive to Arrabida Natural Park and the cliffs of Meco Beach. Head to Cape Espichel with its Sanctuary and stunning Atlantic views. Visit the charming seaside town of Sesimbra and its Moorish Castle. After lunch, explore St. Margareth''s Cave and Portinho da Arrabida harbour. Choose between Arrabida''s hidden golden beaches or a visit to Setubal''s dolphin-community interpretive centre.','Full-day guided tour of Arrabida Natural Park, Sesimbra and Cape Espichel from Lisbon — hotel pickup and air-conditioned minivan.','Arrabida','Hotel pickup in Lisbon',38.4848,-8.9766,45.0,'EUR','8h',NULL,'Outdoors','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/06/73/fb/82.jpg','["https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/06/73/fb/82.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/17/09/1c/ea.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/17/09/1c/ee.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/17/09/1c/ef.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/17/09/1c/f0.jpg"]'::jsonb,NULL,'["Arrabida Natural Park — dramatic limestone cliffs and turquoise sea","Cape Espichel Sanctuary with sweeping Atlantic views","Sesimbra Moorish Castle and medieval old town","St. Margareth''s Cave and Portinho da Arrabida harbour","Hotel pickup and drop-off in Lisbon included"]'::jsonb,'["Hotel pickup and drop-off","Professional guide","Transport by air-conditioned minivan"]'::jsonb,'["English","Portuguese"]'::jsonb,'Free cancellation up to 24h before',4.63,27,'Arrabida',true,231,'https://www.viator.com/en-GB/tours/Lisbon/Arrabida-Natural-Park-and-Sesimbra-Day-Trip-from-Lisbon/d538-6999SMLBIG?pid=P00285354&mcid=42383&medium=link','Viator'),
(40,'Underwater Viewing Tour along the Coast of Sesimbra','Take an unforgettable trip and discover the stunning beauty of the Sesimbra Coast, its secrets and hidden beaches. Our boat, APNEA, has a unique feature: a hull with panoramic windows overlooking the underwater world. This view and the upper platform create a complete, fun and educational tour through the Professor Luiz Saldanha Marine Park — part of the Arrabida Natural Park, including Praia da Ribeira do Cavalo and the secret beaches of this coast.','2h coast tour aboard APNEA — a boat with panoramic underwater windows — through Sesimbra''s Marine Park and hidden beaches.','Sesimbra','Sesimbra Port, Sesimbra',38.4430,-9.1012,18.0,'EUR','2h',NULL,'Micro Adventures','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/12/e7/d9/f2.jpg','["https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/12/e7/d9/f2.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/13/17/2c/a0.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/12/e7/d9/e7.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/13/17/2c/af.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/12/e7/7d/6e.jpg"]'::jsonb,NULL,'["Unique boat with panoramic underwater hull windows","Visit Praia da Ribeira do Cavalo from the sea","Luiz Saldanha Marine Park — one of Portugal''s most protected marine areas","Educational and fun for all ages","Instagram photos with Aquarama frame included"]'::jsonb,'["Insurance","Life jackets","Local guide","Photos including Aquarama frame"]'::jsonb,'["English","Portuguese"]'::jsonb,'Free cancellation up to 24h before',4.83,35,'Sesimbra',true,232,'https://www.viator.com/en-GB/tours/Setubal-District/Underwater-viewing-tours-along-the-coast-of-Sesimbra/d5016-124473P1?pid=P00285354&mcid=42383&medium=link','Viator'),
(40,'Private Jeep Tour from Lisbon — Arrabida, Sesimbra and Beach Picnic','Leave Lisbon behind and dive into a thrilling full-day Jeep adventure through Arrabida Natural Park and Sesimbra — home to some of Europe''s most breathtaking coastal views. Ride off-road through lush landscapes, discover hidden caves, and soak up the sun on pristine beaches like Praia de Galapinhos or Praia das Bicas. Enjoy a private beach picnic in paradise, explore the charming village of Sesimbra, and take in dramatic views from the cliffs of Cabo Espichel. Led by a passionate local guide.','7h private Jeep tour: off-road through Arrabida, secret beaches, Sesimbra village, Cabo Espichel cliffs and a beachside picnic.','Arrabida','Private pickup in Lisbon, Setubal, Almada or Sesimbra',38.4848,-8.9766,109.0,'EUR','7h',NULL,'Outdoors','https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/13/2b/30/fd.jpg','["https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/13/2b/30/fd.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/13/2b/30/ed.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0f/35/b9/0c.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0e/c0/cd/ea.jpg","https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/13/2a/2e/1d.jpg"]'::jsonb,NULL,'["Off-road private Jeep adventure through Arrabida Natural Park","Secret beaches: Praia de Galapinhos and Praia das Bicas","Private beachside picnic — local cheeses, meats, wine and pastries","Sesimbra village and dramatic Cabo Espichel cliffs","Private pickup from Lisbon, Almada, Setubal or Sesimbra"]'::jsonb,'["Private transportation","Bottled water","All fees and taxes","Private picnic with local cheeses, bread, smoked meats, pastries, fruit, wine, juice and water","Air conditioning","Private pick-up and drop-off"]'::jsonb,'["English","Portuguese"]'::jsonb,'Free cancellation up to 24h before',5.0,48,'Arrabida',true,233,'https://www.viator.com/en-GB/tours/Lisbon/Wild-Beaches-and-Picnic-Experience/d538-349639P1?pid=P00285354&mcid=42383&medium=link','Viator');

-- Link all 8 to WOT Soul Costa da Caparica
INSERT INTO hotel_experiences (hotel_id, experience_id, is_active, display_order)
SELECT 'wot-soul-costa-da-caparica', id, true, display_order
FROM experiences
WHERE display_order BETWEEN 226 AND 233
ON CONFLICT (hotel_id, experience_id) DO NOTHING;

-- Verification
SELECT COUNT(*) AS linked_to_caparica FROM hotel_experiences WHERE hotel_id = 'wot-soul-costa-da-caparica';
